version: '3'
services:
  frontend-dev:
    build:
      context: .
    ports:
      - "8081:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
